name: flutter_web_account_book
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore:
  cloud_functions:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_spinkit:
  font_awesome_flutter:
  freezed_annotation:
  gap:
  google_sign_in:
  hooks_riverpod:
  intl:
  json_annotation:
  path_to_regexp:
  shimmer:
  sign_in_button:
  simple_logger:
  tuple:
  uuid:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints: ^2.0.0
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:

flutter:
  uses-material-design: true
